[package]
name = "fhe-exchange"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true }
fhe-core = { workspace = true }

[dev-dependencies]
seal-lib = { path = "../seal-lib" }