stages:
  - check

rust_stable:
  stage: check
  tags:
    - docker
  image: fluteur/rust-cli:latest
  script:
    - git submodule update --init --recursive
    - cargo check --all-features --locked
    - cargo fmt -- --check
    - cargo clippy --workspace -- -D warnings --no-deps
    - cargo test --workspace
