stages:
  - check

rust_stable:
  stage: check
  tags:
    - docker
  image: fluteur/rust-cli:latest
  cache:
    key: rust-cache
    paths:
      - /usr/local/cargo/registry
      - /usr/local/cargo/git
      - /usr/local/cargo/bin
      - target
  script:
    - cargo build
    - cargo fmt -- --check
    - cargo clippy --workspace -- -D warnings
    - cargo test --workspace

rust_nightly_miri:
  stage: check
  tags:
    - docker
  image: rustlang/rust:nightly
  before_script:
    - rustup component add miri
  script:
    - cargo miri test -p fhe-core
