[package]
name = "bpce-fhe"
version = "0.1.0"
edition = "2024"

[dependencies]
ckks-lib = { path = "ckks-lib" }
libm = "0.2.11"
log = "0.4.26"
mimalloc = { version = "0.1.43", features = ["secure"] }
pretty_env_logger = "0.5.0"
rouille = { git = "https://github.com/bnjbvr/rouille.git" }
seal-lib = { path = "seal-lib" }
tokio = { version = "1.43.0", features = ["full"] }
tracing = "0.1.41"
tracing-subscriber = "0.3.19"

[dev-dependencies]
rand = "0.9.0"

[workspace]
members = ["ckks-lib", "fhe-core", "seal-lib"]

[workspace.dependencies]
fhe-core = { path = "fhe-core", features = ["alloc"] }
zeroize = { version = "1.8.1", features = ["alloc", "derive"] }
