[package]
name = "bpce-fhe"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true }
fhe-core = { workspace = true }
log = "0.4.26"
mimalloc = { version = "0.1.43", features = ["secure"] }
pretty_env_logger = "0.5.0"
rouille = { git = "https://github.com/bnjbvr/rouille.git" }
seal-lib = { path = "seal-lib" }
# tokio = { version = "1.43.0", features = ["full"] }

[workspace]
members = ["fhe-core", "seal-lib", "fhe-select"]

[workspace.dependencies]
bincode = "2.0.1"
fhe-core = { path = "fhe-core" }
