[package]
name = "bpce-fhe"
version = "0.1.0"
edition = "2024"

[dependencies]
ckks-lib = { path = "ckks-lib" }
libm = "0.2.11"
[dev-dependencies]
rand = "0.9.0"

[workspace]
members = ["ckks-lib", "fhe-core"]

[workspace.dependencies]
fhe-core = { path = "fhe-core" }
zeroize = { version = "1.8.1", features = ["alloc", "derive"] }
