[package]
name = "bpce-fhe"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true }
clap = { version = "4.5.28", features = ["derive"] }
fhe-core = { workspace = true }
fhe-exchange = { path = "fhe-exchange" }
log = "0.4.26"
mimalloc = { version = "0.1.43", features = ["secure"] }
parquet = { version = "54.2.1", optional = true }
pretty_env_logger = "0.5.0"
seal-lib = { path = "seal-lib" }
thiserror = "2.0.12"
tokio = { version = "1.43.0", features = ["full"] }

[dev-dependencies]
criterion = "0.5.1"
rouille = { git = "https://github.com/bnjbvr/rouille.git" }

[workspace]
members = ["fhe-core", "seal-lib", "fhe-select", "fhe-exchange"]

[workspace.dependencies]
bincode = "2.0.1"
fhe-core = { path = "fhe-core" }

[features]
parquet = ["dep:parquet"]
