[package]
name = "seal-lib"
version = "0.1.0"
edition = "2024"

[dependencies]
bincode = { workspace = true }
fhe-core = { workspace = true }
fhe-operations = { workspace = true }
sealy = { path = "../sealy" }

[[bench]]
name = "seal-lib"
harness = false

[dev-dependencies]
criterion = "0.5.1"
