[package]
name = "fhe-core"
version = "0.1.0"
edition = "2024"

[dependencies]
getrandom = "0.3.1"
libm = "0.2.11"
zeroize = { workspace = true, optional = true }

[features]
alloc = []
zeroize = ["dep:zeroize"]
