[package]
name = "fhe-select"
version = "0.1.0"
edition = "2024"

[dependencies]
fhe-core = { workspace = true }
zeroize = { workspace = true }

[dev-dependencies]
seal-lib = { path = "../seal-lib" }
